<a href="https://colab.research.google.com/github/harshidarahimawork-a11y/finance-data-analysis-python/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [189]:
###Part A — Pandas Fundamentals

In [190]:

#1. Import Pandas and load an Excel file into a DataFrame.

In [191]:
import pandas as pd
import matplotlib.pyplot as plt

In [192]:
df=pd.read_excel("/content/Dirty_Finance_Transactions_Practice.xlsx")

In [193]:
#2. Display the first 5 rows.

In [194]:
df.head()

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description
0,INV-1001,2026-01-05,ABC Traders,Office Supplies,10,1500,15000,0,14000,15000.0,Printer paper
1,INV-1002,05/01/2026,abc traders,Office Supplies,20,2500,50000,0,48000,50000.0,Office chairs
2,INV-1003,2026/01/07,Global Office,Travel,5,3200,16000,0,17000,16000.0,Client visit
3,INV-1004,Jan 08 2026,Prime Supplies,Utilities,8,1800,14400,0,15000,14400.0,Electricity
4,NaN,2026-01-09,ABC Traders,Office Supplies,12,NaN,18000,0,16000,18000.0,Stationery

In [195]:
#3. Display the last 5 rows.

In [196]:
df.tail()

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description
15,INV-1016,2026-01-20,Prime Supplies,Utilities,8,NaN,14400,0,15000,14400.0,Water bill
16,INV-1017,21/01/2026,Tech World,IT Equipment,4,12500,50000,0,52000,50000.0,Laptop purchase
17,INV-1018,2026-01-22,NaN,Travel,11,2100,"23,100",0,22000,23100.0,Client visit
18,INV-1019,23-Jan-2026,ABC Traders,Office Supplies,NaN,"1,500",15500,0,16000,15500.0,Stationery
19,INV-1020,2026-01-24,Global Office,Travel,five,3200,16000,0,17000,16000.0,Taxi expense

In [197]:
#4. Find the number of rows and columns.

In [198]:
df.shape

(20, 11)

In [199]:
#5. Display all column names.

In [200]:
df.columns

Index(['Invoice No', 'Date', 'Supplier', 'Account', 'Quantity', 'UnitPrice',
       'Debit', 'Credit', 'Budget', 'Actual', 'Description'],
      dtype='object')

In [201]:
#6. Check the data type of every column.

In [202]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice No   19 non-null     object
 1   Date         19 non-null     object
 2   Supplier     19 non-null     object
 3   Account      20 non-null     object
 4   Quantity     18 non-null     object
 5   UnitPrice    18 non-null     object
 6   Debit        20 non-null     object
 7   Credit       20 non-null     int64
 8   Budget       20 non-null     int64
 9   Actual       19 non-null     float64
 10  Description  20 non-null     object
dtypes: float64(1), int64(2), object(8)
memory usage: 1.8+ KB

In [203]:
#7. Generate a statistical summary of numeric columns.

In [204]:
df.describe()

       Credit        Budget        Actual
count    20.0     20.000000     19.000000
mean      0.0  26425.000000  27192.105263
std       0.0  16952.934073  17810.049154
min       0.0  11000.000000  10500.000000
25%       0.0  15000.000000  15250.000000
50%       0.0  17000.000000  18000.000000
75%       0.0  37000.000000  37500.000000
max       0.0  72000.000000  75000.000000

In [205]:
#8. Select only Invoice No and Supplier.

In [206]:
df[['Invoice No','Supplier']]

    Invoice No         Supplier
0     INV-1001      ABC Traders
1    INV-1002      abc traders
2     INV-1003    Global Office
3     INV-1004   Prime Supplies
4          NaN      ABC Traders
5     INV-1006       Tech World
6     INV-1007    Global Office
7     INV-1008   Prime Supplies
8     INV-1003    Global Office
9    INV-1010        Tech World
10    INV-1011      ABC Traders
11    INV-1012   Prime Supplies
12    INV-1013       TECH WORLD
13    INV-1014    Global Office
14    INV-1015      ABC Traders
15    INV-1016  Prime Supplies
16    INV-1017       Tech World
17    INV-1018              NaN
18    INV-1019      ABC Traders
19    INV-1020    Global Office

In [207]:
#9. Select Debit and Credit.

In [208]:
df[['Debit','Credit']]

     Debit  Credit
0    15000       0
1    50000       0
2    16000       0
3    14400       0
4    18000       0
5    37500       0
6    10500       0
7    26250       0
8    16000       0
9    50000       0
10   37500       0
11   12600       0
12   75000       0
13   18900       0
14   15000       0
15   14400       0
16   50000       0
17  23,100       0
18   15500       0
19   16000       0

In [209]:
#10. Count missing values in every column.

In [210]:
df.isnull().sum()

Invoice No     1
Date           1
Supplier       1
Account        0
Quantity       2
UnitPrice      2
Debit          0
Credit         0
Budget         0
Actual         1
Description    0
dtype: int64

In [211]:
##Part B — Missing Data & Cleaning

In [212]:
#1. Convert a numeric-looking text column using pd.to_numeric().

In [213]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['UnitPrice']=pd.to_numeric(df['UnitPrice'],errors='coerce')
df['Debit']=pd.to_numeric(df['Debit'],errors='coerce')

In [214]:
#2. Use fillna() to replace missing numeric values with 0.

In [215]:
numeric_cols=df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(0)

In [216]:
df.isna().sum()

Invoice No     1
Date           1
Supplier       1
Account        0
Quantity       0
UnitPrice      0
Debit          0
Credit         0
Budget         0
Actual         0
Description    0
dtype: int64

In [217]:
 #3. Fill missing UnitPrice values using the mean UnitPrice.

In [218]:
mean_unitprice=df['UnitPrice'].mean()
df['UnitPrice']=df['UnitPrice'].replace({0:mean_unitprice})
df['UnitPrice'].value_counts()

UnitPrice
12500.0    4
1500.0     3
3912.5     3
3200.0     3
2100.0     3
1800.0     2
2500.0     1
1750.0     1
Name: count, dtype: int64

In [219]:
#4. Use dropna() and compare row counts before and after.

In [220]:
before = len(df)
print("Rows before dropna:", before)

Rows before dropna: 20

In [221]:
df_clean = df.dropna()
after = len(df_clean)

print("Rows after dropna:", after)

Rows after dropna: 17

In [222]:
print("Rows removed:", before - after)

Rows removed: 3

In [223]:
#5. Find rows where Invoice No is missing.

In [224]:
df[df["Invoice No"].isna()]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description
4,NaN,2026-01-09,ABC Traders,Office Supplies,12.0,3912.5,18000.0,0,16000,18000.0,Stationery

In [225]:
#6. Remove leading/trailing spaces from Supplier names.

In [226]:
df['Supplier']=df['Supplier'].str.title()
df['Supplier']=df['Supplier'].str.strip()

df['Supplier'].head()

0       Abc Traders
1       Abc Traders
2     Global Office
3    Prime Supplies
4       Abc Traders
Name: Supplier, dtype: object

In [227]:
#7. Convert a text column to lowercase using .str.

In [228]:
df['Description']=df['Description'].str.strip().str.lower()
df['Description'].head()

0    printer paper
1    office chairs
2     client visit
3      electricity
4       stationery
Name: Description, dtype: object

In [229]:
#8.Check whether Invoice No contains duplicates.

In [230]:
df['Invoice No'].duplicated().any()

np.True_

In [231]:
#9.Display all rows belonging to duplicated invoices.

In [232]:
df[df['Invoice No'].duplicated()]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description
8,INV-1003,2026-01-07,Global Office,Travel,5.0,3200.0,16000.0,0,17000,16000.0,taxi expense

In [233]:
##Part C — Invoice & Transaction Validation

In [234]:
#1. Create TransactionValue = Quantity × UnitPrice.

In [235]:
df['transaction_value']=df['Quantity']*df['UnitPrice']
df['transaction_value']

0     15000.0
1     50000.0
2     16000.0
3     14400.0
4     46950.0
5     37500.0
6         0.0
7     26250.0
8     16000.0
9     50000.0
10    37500.0
11    12600.0
12    75000.0
13    18900.0
14    15000.0
15    31300.0
16    50000.0
17    23100.0
18        0.0
19        0.0
Name: transaction_value, dtype: float64

In [236]:
#2. Compare TransactionValue with the recorded Debit/Credit amount.

In [237]:
df['comparison']=df['transaction_value']-(df['Debit'])+df['Credit']
df['comparison']

0         0.0
1         0.0
2         0.0
3         0.0
4     28950.0
5         0.0
6    -10500.0
7         0.0
8         0.0
9         0.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15    16900.0
16        0.0
17    23100.0
18   -15500.0
19   -16000.0
Name: comparison, dtype: float64

In [238]:
#3. Create a Validation column showing Valid or Check.

In [239]:
df["validation"] = df["comparison"].apply(
    lambda x: "Valid" if x == 0 else "Check")

df['validation']

0     Valid
1     Valid
2     Valid
3     Valid
4     Check
5     Valid
6     Check
7     Valid
8     Valid
9     Valid
10    Valid
11    Valid
12    Valid
13    Valid
14    Valid
15    Check
16    Valid
17    Check
18    Check
19    Check
Name: validation, dtype: object

In [240]:
#4. Find all transactions requiring checking.

In [241]:
(df['validation']=="Check").sum()

np.int64(6)

In [242]:
#5. Count duplicated invoice numbers.

In [243]:
df['Invoice No'].duplicated().sum()

np.int64(1)

In [244]:
df[df["Invoice No"].duplicated()]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
8,INV-1003,2026-01-07,Global Office,Travel,5.0,3200.0,16000.0,0,17000,16000.0,taxi expense,16000.0,0.0,Valid

In [245]:
#6. Find invoices appearing more than once using value_counts().

In [246]:
df['Invoice No'].value_counts()

Invoice No
INV-1003      2
INV-1001      1
 INV-1002     1
INV-1004      1
INV-1006      1
INV-1007      1
INV-1008      1
INV-1010      1
INV-1011      1
INV-1012      1
INV-1013      1
INV-1014      1
INV-1015      1
INV-1016      1
INV-1017      1
INV-1018      1
INV-1019      1
INV-1020      1
Name: count, dtype: int64

In [247]:
#7.Calculate net transaction amount as Debit − Credit.

In [248]:
net_transaction=df['Debit']-df['Credit']
net_transaction

0     15000.0
1     50000.0
2     16000.0
3     14400.0
4     18000.0
5     37500.0
6     10500.0
7     26250.0
8     16000.0
9     50000.0
10    37500.0
11    12600.0
12    75000.0
13    18900.0
14    15000.0
15    14400.0
16    50000.0
17        0.0
18    15500.0
19    16000.0
dtype: float64

In [249]:
#8. Find transactions with a negative net amount.

In [250]:
df[df['transaction_value']<0]

Empty DataFrame
Columns: [Invoice No, Date, Supplier, Account, Quantity, UnitPrice, Debit, Credit, Budget, Actual, Description, transaction_value, comparison, validation]
Index: []

In [251]:
#9. Create an exception report containing failed validation records.

In [252]:
exception_report = df.loc[
    df["validation"] == "Check",
    [
        "Invoice No",
        "Supplier",
        "transaction_value",
        "Debit",
        "Credit",
        "comparison",
        "validation"
    ]
]

exception_report

,Invoice No,Supplier,transaction_value,Debit,Credit,comparison,validation
4,NaN,Abc Traders,46950.0,18000.0,0,28950.0,Check
6,INV-1007,Global Office,0.0,10500.0,0,-10500.0,Check
15,INV-1016,Prime Supplies,31300.0,14400.0,0,16900.0,Check
17,INV-1018,NaN,23100.0,0.0,0,23100.0,Check
18,INV-1019,Abc Traders,0.0,15500.0,0,-15500.0,Check
19,INV-1020,Global Office,0.0,16000.0,0,-16000.0,Check

In [253]:
#Part D — Filtering & Sorting

In [254]:
#1. Show transactions where Debit is greater than 50,000.

In [255]:
df[df['Debit']>50000]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
12,INV-1013,17-Jan-2026,Tech World,IT Equipment,6.0,12500.0,75000.0,0,72000,75000.0,laptop purchase,75000.0,0.0,Valid

In [256]:
#2. Show transactions where Credit is greater than 25,000.

In [257]:
df[df['Credit']>25000]

Empty DataFrame
Columns: [Invoice No, Date, Supplier, Account, Quantity, UnitPrice, Debit, Credit, Budget, Actual, Description, transaction_value, comparison, validation]
Index: []

In [258]:
#3. Show transactions where UnitPrice is above the average.

In [259]:

df[df['UnitPrice']>mean_unitprice]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
5,INV-1006,10-01-2026,Tech World,IT Equipment,3.0,12500.0,37500.0,0,40000,37500.0,laptop purchase,37500.0,0.0,Valid
9,INV-1010,2026-01-14,Tech World,IT Equipment,4.0,12500.0,50000.0,0,48000,50000.0,monitor purchase,50000.0,0.0,Valid
12,INV-1013,17-Jan-2026,Tech World,IT Equipment,6.0,12500.0,75000.0,0,72000,75000.0,laptop purchase,75000.0,0.0,Valid
16,INV-1017,21/01/2026,Tech World,IT Equipment,4.0,12500.0,50000.0,0,52000,50000.0,laptop purchase,50000.0,0.0,Valid

In [260]:
#4. Filter transactions for one supplier.

In [261]:
df[df['Supplier']=='Abc Traders']

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
0,INV-1001,2026-01-05,Abc Traders,Office Supplies,10.0,1500.0,15000.0,0,14000,15000.0,printer paper,15000.0,0.0,Valid
1,INV-1002,05/01/2026,Abc Traders,Office Supplies,20.0,2500.0,50000.0,0,48000,50000.0,office chairs,50000.0,0.0,Valid
4,NaN,2026-01-09,Abc Traders,Office Supplies,12.0,3912.5,18000.0,0,16000,18000.0,stationery,46950.0,28950.0,Check
10,INV-1011,15/01/2026,Abc Traders,Office Supplies,25.0,1500.0,37500.0,0,36000,37500.0,printer cartridges,37500.0,0.0,Valid
14,INV-1015,19-01-2026,Abc Traders,Office Supplies,10.0,1500.0,15000.0,0,14500,0.0,printer paper,15000.0,0.0,Valid
18,INV-1019,23-Jan-2026,Abc Traders,Office Supplies,0.0,3912.5,15500.0,0,16000,15500.0,stationery,0.0,-15500.0,Check

In [262]:
#5. Show transactions where TransactionValue exceeds 100,000.

In [263]:
df[df['transaction_value']>100000]

Empty DataFrame
Columns: [Invoice No, Date, Supplier, Account, Quantity, UnitPrice, Debit, Credit, Budget, Actual, Description, transaction_value, comparison, validation]
Index: []

In [264]:
#6. Sort by TransactionValue from highest to lowest.

In [265]:
df.sort_values(by='transaction_value',ascending=False)

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
12,INV-1013,17-Jan-2026,Tech World,IT Equipment,6.0,12500.0,75000.0,0,72000,75000.0,laptop purchase,75000.0,0.0,Valid
1,INV-1002,05/01/2026,Abc Traders,Office Supplies,20.0,2500.0,50000.0,0,48000,50000.0,office chairs,50000.0,0.0,Valid
9,INV-1010,2026-01-14,Tech World,IT Equipment,4.0,12500.0,50000.0,0,48000,50000.0,monitor purchase,50000.0,0.0,Valid
16,INV-1017,21/01/2026,Tech World,IT Equipment,4.0,12500.0,50000.0,0,52000,50000.0,laptop purchase,50000.0,0.0,Valid
4,NaN,2026-01-09,Abc Traders,Office Supplies,12.0,3912.5,18000.0,0,16000,18000.0,stationery,46950.0,28950.0,Check
10,INV-1011,15/01/2026,Abc Traders,Office Supplies,25.0,1500.0,37500.0,0,36000,37500.0,printer cartridges,37500.0,0.0,Valid
5,INV-1006,10-01-2026,Tech World,IT Equipment,3.0,12500.0,37500.0,0,40000,37500.0,laptop purchase,37500.0,0.0,Valid
15,INV-1016,2026-01-20,Prime Supplies,Utilities,8.0,3912.5,14400.0,0,15000,14400.0,water bill,31300.0,16900.0,Check
7,INV-1008,2026-01-12,Prime Supplies,Utilities,15.0,1750.0,26250.0,0,25000,26250.0,water bill,26250.0,0.0,Valid
17,INV-1018,2026-01-22,NaN,Travel,11.0,2100.0,0.0,0,22000,23100.0,client visit,23100.0,23100.0,Check
13,INV-1014,2026/01/18,Global Office,Travel,9.0,2100.0,18900.0,0,20000,18900.0,hotel expense,18900.0,0.0,Valid
2,INV-1003,2026/01/07,Global Office,Travel,5.0,3200.0,16000.0,0,17000,16000.0,client visit,16000.0,0.0,Valid
8,INV-1003,2026-01-07,Global Office,Travel,5.0,3200.0,16000.0,0,17000,16000.0,taxi expense,16000.0,0.0,Valid
0,INV-1001,2026-01-05,Abc Traders,Office Supplies,10.0,1500.0,15000.0,0,14000,15000.0,printer paper,15000.0,0.0,Valid
14,INV-1015,19-01-2026,Abc Traders,Office Supplies,10.0,1500.0,15000.0,0,14500,0.0,printer paper,15000.0,0.0,Valid
3,INV-1004,Jan 08 2026,Prime Supplies,Utilities,8.0,1800.0,14400.0,0,15000,14400.0,electricity,14400.0,0.0,Valid
11,INV-1012,2026-01-16,Prime Supplies,Utilities,7.0,1800.0,12600.0,0,13000,12600.0,electricity,12600.0,0.0,Valid
6,INV-1007,NaN,Global Office,Travel,0.0,2100.0,10500.0,0,11000,10500.0,hotel expense,0.0,-10500.0,Check
18,INV-1019,23-Jan-2026,Abc Traders,Office Supplies,0.0,3912.5,15500.0,0,16000,15500.0,stationery,0.0,-15500.0,Check
19,INV-1020,2026-01-24,Global Office,Travel,0.0,3200.0,16000.0,0,17000,16000.0,taxi expense,0.0,-16000.0,Check

In [266]:
#7. Find the highest TransactionValue.

In [267]:
df['transaction_value'].max()

75000.0

In [268]:
#8. Find the lowest TransactionValue.

In [269]:
df['transaction_value'].min()

0.0

In [270]:
#9. Display the top 5 transactions by TransactionValue.

In [271]:
top_5_transactionvalues=df['transaction_value'].nlargest(5)
top_5_transactionvalues

12    75000.0
1     50000.0
9     50000.0
16    50000.0
4     46950.0
Name: transaction_value, dtype: float64

In [272]:
#Part E — Grouping & Finance Analysis

In [273]:
#1. Group by Supplier and calculate total Debit.

In [274]:
df.groupby('Supplier')['Debit'].sum()

Supplier
Abc Traders       151000.0
Global Office      77400.0
Prime Supplies     67650.0
Tech World        212500.0
Name: Debit, dtype: float64

In [275]:
#2. Group by Supplier and calculate total Credit.

In [276]:
df.groupby('Supplier')['Credit'].sum()

Supplier
Abc Traders       0
Global Office     0
Prime Supplies    0
Tech World        0
Name: Credit, dtype: int64

In [277]:
#3. Group by Account and calculate total Debit and Credit.

In [278]:
df.groupby('Account')[['Debit','Credit']].sum()

                    Debit  Credit
Account
IT Equipment     212500.0       0
Office Supplies  151000.0       0
Travel            77400.0       0
Utilities         67650.0       0

In [279]:
#4. Calculate total Debit, total Credit and net balance.

In [280]:
total_debit=df['Debit'].sum()
total_credit=df['Credit'].sum()
net_balance=total_debit-total_credit
print("Total Debit:",total_debit)
print("Total Credit:",total_credit)
print("Net Balance:",net_balance)

Total Debit: 508550.0
Total Credit: 0
Net Balance: 508550.0

In [281]:
#5. Find the account with the highest total Credit.

In [282]:
df['Account'].value_counts()

Account
Office Supplies    6
Travel             6
Utilities          4
IT Equipment       4
Name: count, dtype: int64

In [283]:
df.groupby('Account')['Credit'].max()

Account
IT Equipment       0
Office Supplies    0
Travel             0
Utilities          0
Name: Credit, dtype: int64

In [284]:
#7. Create Variance = Actual − Budget.

In [285]:
variance=df['Actual']-df['Budget']
variance

0      1000.0
1      2000.0
2     -1000.0
3      -600.0
4      2000.0
5     -2500.0
6      -500.0
7      1250.0
8     -1000.0
9      2000.0
10     1500.0
11     -400.0
12     3000.0
13    -1100.0
14   -14500.0
15     -600.0
16    -2000.0
17     1100.0
18     -500.0
19    -1000.0
dtype: float64

In [286]:
#8. Calculate Variance %.

In [287]:
variance_percentage=variance/df['Budget']*100
variance_percentage

0       7.142857
1       4.166667
2      -5.882353
3      -4.000000
4      12.500000
5      -6.250000
6      -4.545455
7       5.000000
8      -5.882353
9       4.166667
10      4.166667
11     -3.076923
12      4.166667
13     -5.500000
14   -100.000000
15     -4.000000
16     -3.846154
17      5.000000
18     -3.125000
19     -5.882353
dtype: float64

In [288]:
#9. Identify records where Actual is above Budget.

In [289]:
df[df["Actual"] > df["Budget"]]

,Invoice No,Date,Supplier,Account,Quantity,UnitPrice,Debit,Credit,Budget,Actual,Description,transaction_value,comparison,validation
0,INV-1001,2026-01-05,Abc Traders,Office Supplies,10.0,1500.0,15000.0,0,14000,15000.0,printer paper,15000.0,0.0,Valid
1,INV-1002,05/01/2026,Abc Traders,Office Supplies,20.0,2500.0,50000.0,0,48000,50000.0,office chairs,50000.0,0.0,Valid
4,NaN,2026-01-09,Abc Traders,Office Supplies,12.0,3912.5,18000.0,0,16000,18000.0,stationery,46950.0,28950.0,Check
7,INV-1008,2026-01-12,Prime Supplies,Utilities,15.0,1750.0,26250.0,0,25000,26250.0,water bill,26250.0,0.0,Valid
9,INV-1010,2026-01-14,Tech World,IT Equipment,4.0,12500.0,50000.0,0,48000,50000.0,monitor purchase,50000.0,0.0,Valid
10,INV-1011,15/01/2026,Abc Traders,Office Supplies,25.0,1500.0,37500.0,0,36000,37500.0,printer cartridges,37500.0,0.0,Valid
12,INV-1013,17-Jan-2026,Tech World,IT Equipment,6.0,12500.0,75000.0,0,72000,75000.0,laptop purchase,75000.0,0.0,Valid
17,INV-1018,2026-01-22,NaN,Travel,11.0,2100.0,0.0,0,22000,23100.0,client visit,23100.0,23100.0,Check

In [290]:
#10. Create a management summary with Budget, Actual, Variance and Variance %.

In [291]:
management_summary=pd.DataFrame({"Budget":df['Budget'],
                               "Actual":df['Actual'],
                               "Variance":variance,
                               "Variance Percentage":variance_percentage
    })
management_summary

    Budget   Actual  Variance  Variance Percentage
0    14000  15000.0    1000.0             7.142857
1    48000  50000.0    2000.0             4.166667
2    17000  16000.0   -1000.0            -5.882353
3    15000  14400.0    -600.0            -4.000000
4    16000  18000.0    2000.0            12.500000
5    40000  37500.0   -2500.0            -6.250000
6    11000  10500.0    -500.0            -4.545455
7    25000  26250.0    1250.0             5.000000
8    17000  16000.0   -1000.0            -5.882353
9    48000  50000.0    2000.0             4.166667
10   36000  37500.0    1500.0             4.166667
11   13000  12600.0    -400.0            -3.076923
12   72000  75000.0    3000.0             4.166667
13   20000  18900.0   -1100.0            -5.500000
14   14500      0.0  -14500.0          -100.000000
15   15000  14400.0    -600.0            -4.000000
16   52000  50000.0   -2000.0            -3.846154
17   22000  23100.0    1100.0             5.000000
18   16000  15500.0    -500.0            -3.125000
19   17000  16000.0   -1000.0            -5.882353

In [292]:
#Part F — Practical Finance Challenges

In [293]:
#1. Create an invoice exception report containing duplicates, missing values and validation failures.

In [301]:
invoice_exception_report=pd.DataFrame({"Invoice Duplicates":df.loc[df['Invoice No'].duplicated(), 'Invoice No'],
                                       "Missing Values":df.isnull().sum(),
                                       "Validation Failures":df['validation']

})
invoice_exception_report

                  Invoice Duplicates  Missing Values Validation Failures
0                                NaN             NaN               Valid
1                                NaN             NaN               Valid
2                                NaN             NaN               Valid
3                                NaN             NaN               Valid
4                                NaN             NaN               Check
5                                NaN             NaN               Valid
6                                NaN             NaN               Check
7                                NaN             NaN               Valid
8                           INV-1003             NaN               Valid
9                                NaN             NaN               Valid
10                               NaN             NaN               Valid
11                               NaN             NaN               Valid
12                               NaN             NaN               Valid
13                               NaN             NaN               Valid
14                               NaN             NaN               Valid
15                               NaN             NaN               Check
16                               NaN             NaN               Valid
17                               NaN             NaN               Check
18                               NaN             NaN               Check
19                               NaN             NaN               Check
Account                          NaN             0.0                 NaN
Actual                           NaN             0.0                 NaN
Budget                           NaN             0.0                 NaN
Credit                           NaN             0.0                 NaN
Date                             NaN             1.0                 NaN
Debit                            NaN             0.0                 NaN
Description                      NaN             0.0                 NaN
Invoice No                       NaN             1.0                 NaN
Quantity                         NaN             0.0                 NaN
Supplier                         NaN             1.0                 NaN
UnitPrice                        NaN             0.0                 NaN
comparison                       NaN             0.0                 NaN
transaction_value                NaN             0.0                 NaN
validation                       NaN             0.0                 NaN

In [ ]:
#2. Create a supplier summary with transaction count, total Debit, total Credit and net amount.

In [305]:
supplier_summary = df.groupby('Supplier').agg(
    Transaction_Count=('Supplier', 'size'),
    Total_Debit=('Debit', 'sum'),
    Total_Credit=('Credit', 'sum')
)
supplier_summary['Net Amount'] = supplier_summary['Total_Debit'] - supplier_summary['Total_Credit']
supplier_summary

                Transaction_Count  Total_Debit  Total_Credit  Net Amount
Supplier
Abc Traders                     6     151000.0             0    151000.0
Global Office                   5      77400.0             0     77400.0
Prime Supplies                  4      67650.0             0     67650.0
Tech World                      4     212500.0             0    212500.0

In [303]:
df['Supplier'].count()

np.int64(19)

In [ ]:
#3. Export the cleaned DataFrame to a new Excel file.

In [306]:
df.to_excel("Cleaned_Finance_Transactions.xlsx", index=False)